### ISSUE TITLE
consider both uniqBy and uniqWith style APIs

### ISSUE THREAD

**Issue by michaelficarra** [tc39/proposal-array-unique#10]
As discussed in plenary, @jack-works https://es.discourse.group/t/array-prototype-uniqby/138.

**Comment by michaelficarra** [comment]
@TechQuery I don't know if 0df27fa2fc942291d375797bb1d8fe09ef2d8245 actually addressed this issue. What I'm trying to get at is that there's (at least) two possible APIs here, each with their own benefits and drawbacks. We should choose one or both of them and document the decision-making process.

**Comment by TechQuery** [comment]
This proposal was similar with `uniqWith()`, which has a `.sort()`-like callback: ce01909.
But I think it was more difficult to learn than `.map()`-like callback, so I refactored it.
