### ISSUE TITLE
Change another name (Web compatibility)

### ISSUE THREAD

**Issue by Jack-Works** [tc39/proposal-array-unique#13]
`Array.prototype.unique` has been used in [https://mootools.net/more/docs/1.3.2.1/Types/Array.Extras#Array:unique](https://mootools.net/more/docs/1.3.2.1/Types/Array.Extras#Array:unique).

They add it as a `enumerable` property so it faces the same situation as the `flatten`. We must change another name for it.

**Comment by TechQuery** [comment]
I may choose `uniqueBy`, as [this post](https://es.discourse.group/t/array-prototype-uniqby/138/4?u=techquery) said.
