### ISSUE TITLE
Does .unique() mutate the original array?

### ISSUE THREAD

**Issue by Pokute** [tc39/proposal-array-unique#4]
`README.md` doesn't adequately convey whether `Array.prototype.unique()` modifies the array or whether it returns a new array.

> 1. no parameter, it'll work as [...new Set(array)];
Seems to create a new array since it implies `data.unique()` instead of `data = data.unique()`.

> 2. one index-key parameter (Number, String or Symbol), it'll get values from each array element with the key, and then deduplicates the origin array based on these values;
The "**deduplicates the origin array**" implies mutating the original array.

For case 3, the above applies.

[Typical cases](https://github.com/TechQuery/array-unique-proposal#typical-cases) section doesn't give any hints either. It would help if there was a simple `data`-row with returned value in comment indicating whether it was either modified or not.

Finally, the TypeScript polyfill looks like it doesn't modify the original array.

**Comment by Jack-Works** [comment]
I think mutating the original array is a bad design. We should avoid it in new methods.

**Comment by hax** [comment]
We should make it clear in README that the method return a new array.

**Comment by TechQuery** [comment]
dfab433
