### ISSUE TITLE
The semantic of 0,-0,NaN

### ISSUE THREAD

**Issue by hax** [tc39/proposal-array-unique#5]
It seems the proposal choose `SameValueZero` which follow `Set` and `Array.prototype.includes()`. I'm ok with that, I only create this issue to make sure everyone is happy with that.

**Comment by hax** [comment]
I feel maybe we could reconsider the semantic of `NaN`.

`NaN` is a special value which normally indicate a wrong math operations, so maybe we should bypass them (aka. do not dedupe them)

Note, `Set` or `includes` cases are different, because if treat `NaN` not same as `NaN`, u can't tell whether a Set/array contains `NaN`.

**Comment by TechQuery** [comment]
> Note, `Set` or `includes` cases are different, because if treat `NaN` not same as `NaN`, u can't tell whether a Set/array contains `NaN`.

more explanation?

**Comment by hax** [comment]
If treat `NaN` not same as `NaN`, both `[].includes(NaN)` and `[NaN].includes(NaN)` would return `false`. So existence test have to treat `NaN` as normal value. 

But dedupe is not existence test.

```js
const data = [
  {type: 1}, 
  {type: 1}, 
  {type: 1, name: 'A'}, 
  {type: 1, name: 'B'},
  {type: 1, name: 'B'},
  {type: 2},
  {type: 2, name: 'A'},
]
data.unique(x => x.type + x.name)
```

In this case, dev expect the result have 5 items, but actually 4, because both `{type: 1}` and `{type: 2}` result in `NaN`. 

Of coz we can argue this is the bug of the code. But `NaN` normally means there is something wrong. There is a famous word "Happy families are all alike; every unhappy family is unhappy in its own way". `NaN` just like unhappy family in its own way, so should not be dedup 😂
